### PR TITLE
Flatten and new chars

### PR DESCRIPTION
**Pull request by maaikevanleuken**
@samuelmr please review. Structure has been flattened (issue #14) and characteristics have been added (issue #16). The js file still needs to be adjusted accordingly.

### CODE REVIEW

**Comment by samuelmr** [comment]
`downloadWebwallet` is misleading since you don't download a web app.

**Comment by samuelmr** [comment]
Some camel-cased attribute names have been converted to lower-case, e.g., `credExchangeProtocol` => `credexchangeprotocol` and `connectionTypes` => `connectiontypes`. IMHO, camel-cased versions are easier to read.

**Comment by samuelmr** [comment]
This PR splits the JSON file into a multiple files. OK by me, but I thought that was still under discussion...

**Comment by samuelmr** [comment]
Succestion for naming download and other links:
`downloadAppstore` => `urlAppStore`
`downloadPlaystore` => `urlPlayStore`
`downloadWebWallet` => `urlWebApp`
`website` => `urlWebsite`

**Comment by maaikevanleuken** [comment]
Can we also remove "webApp", as we already have "urlWebApp"?

**Comment by maaikevanleuken** [comment]
> This PR splits the JSON file into a multiple files. OK by me, but I thought that was still under discussion...

Indeed, will be removed. Will add later. For now, just flattened_wallets can be used.

**Review by samuelmr — APPROVED** [review]
LGTM

**Pull request merged**
