### PR TITLE
added hightrust.id

### PR DESCRIPTION
**Pull request by akolio**

### CODE REVIEW

**Comment by cre8** [comment]
Hi @akolio,

are you able to sign your commit so the DCO check can pass? Then we are able to merge your PR :)

**Comment by akolio** [comment]
Thanks @cre8!
Luckily GitHub had straightforward steps to add the signoff.

**Comment by samuelmr** [comment]
I'm not opposed to adding Hightrust.id, but wondering why the entry is basically blank.

@akolio, is there a reason you didn't provide more information? If you're affiliated with Hightrust, it should be relatively easy for you to find out information about supported credential formats, signature algorithms, etc.

At least the `urlWebsite` would be nice (it's mandatory in the schema) so that the audience has a pointer on where to look for more information.

@cre8, I think we shouldn't accept blank entries. They provide very little value to the audience. I removed many entries from the previous iteration due to missing data.

**Comment by akolio** [comment]
We were planning on adding fields as we go. Company URL was added as CompanyUrl which is what the "add wallet" tool on https://openwallet-foundation.github.io/digital-wallet-and-agent-overviews-sig/ wanted. But I see it might be deprecated.

I noticed there were other differences in this json too compared to the ones on GitHub. E.g. there's no "linkToApp" (instead there are fields such as "urlAppStore", "urlGooglePlayStore" and "urlWebsite").
The add wallet tool might need a little refreshing 🙂

**Comment by samuelmr** [comment]
Thanks!

@cre8, will you check that the attributes in the `add` component correspond to the schema?

**Comment by cre8** [comment]
@samuelmr I commented the check out since we had the old schemas included, see: https://github.com/openwallet-foundation/digital-wallet-and-agent-overviews-sig/blob/main/.github/workflows/main.yml#L41

I will add it again

**Pull request merged**
