### PR TITLE
Update Procivis entities

### PR DESCRIPTION
**Pull request by bandirom**

### CODE REVIEW

**Comment by cre8** [comment]
Hi @bandirom,
are you able to sign your comments so the DCO check will run successfully?

**Comment by bandirom** [comment]
> Hi @bandirom, are you able to sign your comments so the DCO check will run successfully?
Hi @cre8 ,
It still a draft as we want to provide bit more information about supported stuff in our project (e.g. signing algh ML-DSA) I work with my local fork and will update this PR ASAP. Thank you!

**Comment by bandirom** [comment]
Hi @cre8,
We are ready for review ;)  
I'll sign commits

**Review by cre8 — APPROVED** [review]
LGTM

**Pull request merged**
